seq_name: ./asset/model/KhanomTanLLM-1B
shl_path: ./asset/model/model_89.pth
ft_model: ./asset/model/thai_tts/model/model_850000.pt
vocab_file: ./asset/model/thai_tts/vocab.txt
rollback: ./asset/rollback.json
asr_path: ./asset/model/thonburain-whisper



